require("core.plugin_configs.telescope")
require("core.plugin_configs.treesitter")
require("core.plugin_configs.lsp")
require("core.plugin_configs.evil-lualine")
require("core.plugin_configs.gitsigns")
