import = [
    "~/.config/alacritty/themes/monokai.toml"
]

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "Fira Code"

[window]
decorations = "none"
dynamic_title = true
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
